### ISSUE TITLE
Compilation warning

### ISSUE THREAD

**Issue by bgranzow** [ibaned/scimod#1]
Warning in  scimod.c

cc -g -O0 -std=c99   -c -o scimod.o scimod.c
scimod.c:165:11: warning: enumeration values 'LOOP', 'SHELL', and 'GROUP' not handled in switch [-Wswitch]
  switch (obj->type) {

**Comment by ibaned** [comment]
-Wno-switch

**Comment by ibaned** [comment]
seriously, this has been a dilemma for me.
Do I enter empty cases for these switches ?
Maybe.
If you make a PR that does that I'll probably merge it.
