### ISSUE TITLE
delete geometric entities

### ISSUE THREAD

**Issue by bgranzow** [ibaned/scimod#2]
Could there be an API function for the deletion of geometric entities (point, line, surface, volume)?
For example, in disk_in_square.c, a surface is created for the disk and meshed.
If the disk is actually void, it would be convenient to have an API to delete it,
so that gmsh knows it is an actual void.

**Comment by ibaned** [comment]
free_object ought to do that.

https://github.com/ibaned/scimod/blob/master/scimod.h#L53

Note however that it doesn't do the right thing
if another object is using the object that gets
deleted.
In order for that to get handled properly,
we would need "upward adjacencies".

**Comment by ibaned** [comment]
Along those same lines, if you want the disk left
out you should skip the add_to_group:

https://github.com/ibaned/scimod/blob/master/disk_in_square.c#L15

That alone will hide it from Gmsh, but may leave a memory
leak. free_object would handle the memory leak.
